version: "3.7"
services:
     
  app:
    build: .
    depends_on:
      - prometheus
    restart: always
    volumes:
      - ./app/:/code/app/
    command: uvicorn app.api:app --reload --host 0.0.0.0 --port 80
    ports:
      - "8080:80"

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
